#Set map type
map_type: costmap

#Set the tolerance we're willing to have for tf transforms
transform_tolerance: 1.0

#Obstacle marking parameters
obstacle_range: 2.5
max_obstacle_height: 2.0
raytrace_range: 3.0

#The footprint of the robot 
footprint: [ [0.200, -0.200], [-0.200, -0.200], [-0.200, 0.200], [0.200, 0.200] ]

#Inscribed and circumscribed radius 
inscribed_radius: 0.15
circumscribed_radius: 0.25

#Cost function parameters
inflation_radius: 0.3
cost_scaling_factor: 10.0

#The cost at which a cell is considered an obstacle when a map is read from the map_server
lethal_cost_threshold: 100

#Configuration for the sensors that the costmap will use to update a map
observation_sources: base_scan

base_scan: {sensor frame: laser, data_type: LaserScan, topic: scan, expected_update_rate: 1.5, observation_persistence: 0.0, marking: true, clearing: true}