DWAPlannerROS:
  #Robot Configuration Parameters
  acc_lim_x: 2.5 #d 2.5
  acc_lim_y: 2.5 #d 2.5
  acc_lim_th: 3.2 #d 3.2

  max_vel_trans: 0.25 #d 0.55
  min_vel_trans: 0.01 #d 0.1
  max_vel_x: 0.25 #d 0.55
  min_vel_x: -0.25 #d 0.0
  max_vel_y: 0.25 #d 0.1
  min_vel_y: -0.25 #d -0.1
  max_vel_theta: 1.0 #d 1.0
  min_vel_theta: 0.1 #d 0.4
  
  #For this example, we'll use a holonomic robot
  holonomic_robot: true

  #Goal Tolerance Parameters
  xy_goal_tolerance: 0.10 #default 0.10
  yaw_goal_tolerance: 0.10 #default 0.05
  latch_xy_goal_tolerance: false #default false

  #Forward Simulation Parameters
  sim_time: 1.0 #default 1.7
  sim_granularity: 0.025 #d 0.025
  vx_samples: 3 #d 3
  vy_samples: 10 #d 10
  vth_samples: 20 #d 20
  controller_frequency: 5.0 #d 20.0

  #Parameters for scoring trajectories
  path_distance_bias: 32.0 #default 32.0
  goal_distance_bias: 24.0 #default 24.0
  occdist_scale: 0.01 #default 0.01
  forward_point_distance: 0.325 #default 0.325
  scaling_speed: 0.25 #default 0.25
  max_scaling_factor: 0.2 #default 0.2
  stop_time_buffer: 0.2 #default 0.2
  publish_cost_grid: false #default false

  #Oscillation Prevention Parameters
  oscillation_reset_dist: 0.05 #default 0.05

  #Global Plan Parameters
  prune_plan: true #default true
