local_costmap:

  #Set the global and robot frames for the costmap
  global_frame: map
  robot_base_frame: robot_frame

  #Set the update and publish frequency of the costmap
  update_frequency: 2.5
  publish_frequency: 1.0
  #We'll configure this costmap to be a rolling window... meaning it is always centered at the robot
  static_map: false
  rolling_window: true
  width: 3.0
  height: 3.0
  resolution: 0.05
